application: miigaik-schedule-ng
version: 1-6-raspvuzov2
runtime: python27
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /tasks/update_db
  script: save_new_version.py
  login: admin
- url: /tasks/clean_oldest
  script: garbage_collector.py
  login: admin
- url: /tasks/upload_api_v2
  script: upload_api_v2.py
  login: admin
- url: .*
  script: main.py

threadsafe: no

libraries:
- name: django
  version: "1.2"
