application: miigaik-schedule-ng
version: 1-2-prod-r4
runtime: python27
api_version: 1

handlers:
- url: /static
  static_dir: static
- url: /tasks/update_db
  script: save_new_version.py
  login: admin
- url: /tasks/clean_oldest
  script: garbage_collector.py
  login: admin
- url: .*
  script: main.py

threadsafe: no

libraries:
- name: django
  version: "1.2"
